# Generated by Django 4.1.4 on 2022-12-22 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('s_tienda', '0003_rename_created_date_variacion_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago_id', models.CharField(max_length=100)),
                ('metodo_pago', models.CharField(max_length=100)),
                ('importe_pagado', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('direccion_1', models.CharField(max_length=50)),
                ('direccion_2', models.CharField(blank=True, max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('nota_pedido', models.CharField(blank=True, max_length=100)),
                ('total_pedido', models.FloatField()),
                ('tax', models.FloatField()),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Aceptado', 'Aceptado'), ('Completado', 'Completado'), ('Cancelado', 'Cancelled')], default='Nuevo', max_length=10)),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('esta_ordenado', models.BooleanField(default=False)),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.pago')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_producto', models.FloatField()),
                ('ordenado', models.BooleanField(default=False)),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.pago')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_tienda.producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variaciones', models.ManyToManyField(blank=True, to='s_tienda.variacion')),
            ],
        ),
    ]
