# Generated by Django 4.1.4 on 2022-12-20 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('s_tienda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carro_id', models.CharField(blank=True, max_length=250)),
                ('fecha_agregada', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarroItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('carro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carrito.carro')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_tienda.producto')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
