# Generated by Django 4.1.4 on 2022-12-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_tienda', '0003_rename_created_date_variacion_fecha_creacion'),
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carroitem',
            name='variaciones',
            field=models.ManyToManyField(blank=True, to='s_tienda.variacion'),
        ),
    ]
