# Generated by Django 4.1.4 on 2022-12-21 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variacion_categoria', models.CharField(choices=[('color', 'color'), ('tamaño', 'tamaño')], max_length=100)),
                ('variacion_valor', models.CharField(max_length=100)),
                ('es_activo', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_tienda.producto')),
            ],
        ),
    ]
