# Generated by Django 4.1.4 on 2022-12-21 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('s_tienda', '0002_variacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variacion',
            old_name='created_date',
            new_name='fecha_creacion',
        ),
    ]
