# Generated by Django 4.1.4 on 2022-12-24 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('s_tienda', '0003_rename_created_date_variacion_fecha_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoración',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(blank=True, max_length=100)),
                ('reseña', models.TextField(blank=True, max_length=500)),
                ('valoracion', models.FloatField()),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_de_creación', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_tienda.producto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
