# Generated by Django 4.1.4 on 2022-12-24 10:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('s_tienda', '0004_valoración'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Valoración',
            new_name='Valoracion',
        ),
    ]
