# Generated by Django 4.1.4 on 2022-12-24 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('s_tienda', '0005_rename_valoración_valoracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(max_length=255, upload_to='tienda/productos')),
                ('producto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='s_tienda.producto')),
            ],
            options={
                'verbose_name': 'Galeria Foto',
                'verbose_name_plural': 'Galeria Fotos',
            },
        ),
    ]
